# Using Activity types to trigger a workflow.
name: Events Demo 1

on:
  pull_request:
    # Specifying the activity types.
    types:
      - opened
      - reopened
    # Specifying the activity filters.
    branches:
      - main
      # - 'dev-*'         ==> Covers all these branches: dev-new dev-updated
      # - 'feat/**'       ==> Covers all these branches: feat/new feat/button feat/new/input

  push:
    # Specifying the activity filters.
    branches:
      - main
      # - 'dev-*'         ==> Covers all these branches: dev-new dev-updated
      # - 'feat/**'       ==> Covers all these branches: feat/new feat/button feat/new/input

    paths-ignore:
      # Don;t run workflow if there are any file changes to below path.
      - ".github/workflows/*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Output Event Data
        run: echo "${{ toJSON(github.event) }}"
      - name: Download Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy Project
        run: echo "Deploying Project..."
