name: First Dummy Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        run: echo "Hello User!!!"
      - name: Say Goodbye
        run: echo "Good to see you, Good-bye!"
